# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: deploy PHP app to Azure Web App - plin-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - run: |
#          curl -X PUT -u '$plin-deploy:jA5KJK21FbaKdMJs8SbauNSwh2Rv1ufy9buZpbNwMxm3ez7LHGMfSlCxErja' https://plin-deploy.scm.azurewebsites.net/api/zipdeploy -H "Content-Type: application/json" -d "{'packageUri':'https://github.com/plin-qiagen/Laravel-vue/releases/download/v8/pimsv2-v8.zip'}"
#          az extension add --name webapp


