# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Release Pims V2 project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Run composer install
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: pimsv2.zip
          exclusions: '*.git* .editorconfig'
#          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: pimsv2
          path: pimsv2.zip
          retention-days: 1

  release-project:
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: pimsv2

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./pimsv2.zip
          asset_name: pimsv2-v${{ github.run_number }}.zip
          asset_content_type: application/zip


#  deploy-project:
#    name: Deploy project to azure
#    runs-on: ubuntu-latest
#    needs: release-project
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: php-app
#
#      - name: Login to Azure
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: 'Deploy to Azure Web App'
#        uses: azure/webapps-deploy@v2
#        id: deploy-to-webapp
#        with:
#          app-name: 'plin-demo'
#          slot-name: 'Production'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_169FCAB39509429D98EE21E10E8647E6 }}
#          package: .